version: "1"
rules:
  - base: alpha
    upstream: UsergeTeam:alpha
    mergeMethod: merge
    mergeUnstable: false
  - base: beta
    upstream: UsergeTeam:beta
    mergeMethod: merge
  - base: master
    upstream: UsergeTeam:master
    mergeMethod: merge
